sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t michalpowaga/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true michalpowaga/docker-react npm test -- --coverage

before_deploy: "echo 'deployment is about to start!'"

deploy:
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "docker-react-v3"
    env: "DockerReactV3-env"
    bucket_name: "elasticbeanstalk-eu-central-1-442152860333"
    bucket_path: "docker-react-v3"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: "$AWS_ACCESS_KEY_SECRET"