sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t michalpowaga/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true michalpowaga/docker-react npm test -- --coverage