sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t michalpowaga/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true mcihalpowaga/docker-react npm run test